CREATE TABLE IF NOT EXISTS COMMAND_LOG (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    device_id VARCHAR(255) NOT NULL,
    command_type VARCHAR(50) NOT NULL,
    payload CLOB,
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);